<?php

$projects_database = [
	
	[	
		"id" => 0,
		"thumbnail" => "modules/images/popcorn.jpg",
		"title" => "Responsive Layout",
		"category" => "HTML, CSS",
		"description" => "This is a site for fans of popcorn in all its deliciousness. It contains a header, a welcome section, some profile cards, and a footer",
		"goal" => "The goal was to  create a website that looks good and is responsive on every sized viewport",
		"process" => "Used the flex box layout module and changed its property values at different viewport sizes using media queries",
		"link" => "https://peprojects.dev/alpha-3/shayne/projects/responsive-layout/",
		"caseStudy" => "?page=case-study",
		"rectangle-image-1" =>"images/popcorn-rectangle-1.png",
		"rectangle-image-2" =>"images/popcorn-rectangle-2.png",
		"horizontal-image-1" =>"images/popcorn-horizontal-1.png",
		"horizontal-image-2" =>"images/popcorn-horizontal-2.png",
	],

	[	"id" => 1,
		"thumbnail" => "images/vr-thumbnail.png",
		"title" => "Tech Brochure",
		"category" => "HTML, CSS",
		"description" => "This is a brochure website for a life-style VR tech device. It's responsive at every viewport and contains buttons and links with hover states. ",
		"goal" => "The goal was to style a website utilizing a prebuilt base code without changing the HTML. ",
		"process" => "Using CSS and PHP (the base code is a collection of php modules) I  navigated through multiple files to style the basecode without touching the HTML. I kept track of all my changes by using comments and writing my code at the bottome of the main css document.",
		"link" => "https://peprojects.dev/alpha-3/shayne/projects/tech-brochure-version-3/",
		"caseStudy" => "?page=case-study",
		"rectangle-image-1" =>"images/tech-rectangle-1.png",
		"rectangle-image-2" =>"images/tech-rectangle-2.png",
		"horizontal-image-1" =>"images/tech-horizontal-1.png",
		"horizontal-image-2" =>"images/tech-horizontal-2.png",
	],

	[	"id" => 2,
		"thumbnail" => "images/php-exercise.jpg",
		"title" => "Forms with PHP",
		"category" => "HTML, PHP",
		"description" => "This project is a collection of different forms generated using PHP. Some programs will create a madlib. Other forms will display mathmatical calculations. ",
		"goal" => "The goal was to get practice with php by creating simple programs based on the exercises from Brian Hogan's Exercises for Programmers (2015)",
		"process" => "I combined PHP and HTML to produce a form that on submission produces a series of outputs based on conditional php statements",
		"link" => "https://peprojects.dev/alpha-3/shayne/projects/php/forms/",
		"caseStudy" => "?page=case-study",
			"rectangle-image-1" =>"images/php-rectangle-1.png",
		"rectangle-image-2" =>"images/php-rectangle-2.png",
		"horizontal-image-1" =>"images/php-horizontal-1.png",
		"horizontal-image-2" =>"images/php-horizontal-2.png",
	],

]; ?>